// <auto-generated />
namespace Assignment9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_FileName_MediaItem_Track : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_FileName_MediaItem_Track));
        
        string IMigrationMetadata.Id
        {
            get { return "201611260433092_add_FileName_MediaItem_Track"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
