// <auto-generated />
namespace Assignment9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_ArtistMediaItem_MediaItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_ArtistMediaItem_MediaItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201611240414404_edit_ArtistMediaItem_MediaItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
